### PR TITLE
Fixed typographical error, changed abreviation to abbreviation in README.

### PR DESCRIPTION
**Pull request by orthographic-pedant**
imayhaveborkedit, I've corrected a typographical error in the documentation of the [borkedbot](https://github.com/imayhaveborkedit/borkedbot) project. You should be able to merge this pull request automatically. However, if this was intentional or you enjoy living in linguistic squalor please let me know and [create an issue](https://github.com/thoppe/orthographic-pedant/issues/new) on my home repository.

### CODE REVIEW

**Comment by imayhaveborkedit** [comment]
Ah, right, readme stuff.  I was going to rewrite the whole thing anyways, but if it un-rustles your jimmies I can merge it.

**Comment by GrappigPanda** [comment]
https://github.com/thoppe/orthographic-pedant

**Comment by imayhaveborkedit** [comment]
Oh it actually is a bot.  I had the passing thought that they did this kind of thing but oh well it doesn't matter it can fix my typos when I rewrite the damn thing anyways.

**Comment by orthographic-pedant** [comment]
Let's call it a supervised bot. It's only three days old (and still
learning) so its parents are still around.

**Pull request merged**
