### PR TITLE
Stability and clarity fixes

### PR DESCRIPTION
**Pull request by GrappigPanda**
Disregard the amount of deletions/additions. They're mostly concerning PEP8 (albeit I didn't fully commit to pep8. Your project, your code styling.). I mostly stuck to pep8 whenever I thought that it genuinely increased readability.

Moreover, I've managed to get it, in it's current form, to run on multiple machines, including: Windows 10 and Ubuntu 14*. Both 64 bit. 

ADD: support for a remote redis server. See the new auth.py with the new variables REDIS_HOST and REDIS_PORT. 

If I have the time, I'll try and tackle an issue or two tomorrow. Good luck, it's a lot of changes.

### CODE REVIEW

**Comment by imayhaveborkedit** [comment]
Some of these things i'm going to have to veto.  Despite being implemented as one, the secrets modules aren't really modules, just config files in python for convenience.  Some commented code should stay as well.  It's a lot to look through but most of it seems fine.

**Comment by GrappigPanda** [comment]
I mainly removed comment code because it clutters up code. Plus it's always in the repo, but your call. I think the only secret module I really gave the module treatment was moderation.py because there was an explicit call for it's regex in a file and it wouldn't compile without having a an import.

**Comment by GrappigPanda** [comment]
If you want me to change anything up, I can edit and make another pull request sometime tomorrow.

**Comment by GrappigPanda** [comment]
Have you had a chance to look over this pull request? I've been wanting to fix some issues, but without knowing if it's going to be merged, I'm not certain which version I should be working with.

**Comment by imayhaveborkedit** [comment]
Since these basically all cosmetic changes i'll just go over every file and make the changes myself.

**Pull request closed without merging**
