### PR TITLE
Added info for secrets

### PR DESCRIPTION
**Pull request by imayhaveborkedit**

### CODE REVIEW

**Comment by GrappigPanda** [comment]
Thanks. The last pull I did, I was having issues fully getting it to load all modules, but I'm going to try again and raise any issues if/when I find. If you wanted to know where I was having issues, it was in https://github.com/imayhaveborkedit/borkedbot/blob/master/modules/dota.py having to do with the global variable "enabled_channels." If the database has yet to be created, it fails to load the module and the bot can't actually run without it.

There's several ways for this to be fixed, but I think editing the entry point for the module to load the database and checking for errors there, then creating a database may be a good way of going about this. The global variable, however, I don't think is a strong candidate.

**Comment by imayhaveborkedit** [comment]
The enabled channels variable is a sort of lazy hack to build a list of channels in one line because the settings module raises exceptions when it can't find a key.  I would imagine I would change this by just changing it into two functions, `get_enabled_channels()` and `get_chanel_info()` or something of the sort.  You can just create an empty list key for "dota_enabled_channels" in the database and that should make it not break.  The entire dota module is weird and messy and a large part of the reason I want to completely restructure the bot, but the restructuring process is a slow and very carefully planned one that has yet to happen.

**Comment by GrappigPanda** [comment]
I noticed that too. I was working on refactoring the whole steam api calls because it was really difficult for me to follow the logic, but I'll be working on it every now and again so expect some more pull requests. I have too much free time at work... yikes.

**Comment by imayhaveborkedit** [comment]
Steam api calls are a different story entirely.  I never ended up using the dotaAPIcalls dict for anything, and I sort of copied over the same format from the twitchapi module.  The functions them selves, mostly the `args = {k:v for k,v in locals().items() if v is not None}` line is for collecting argument calls only if they were used.  Its a bit ugly but it's really easy to copy paste.

**Comment by GrappigPanda** [comment]
I was mostly talking about the "enable_channel" function in https://github.com/imayhaveborkedit/borkedbot/blob/master/modules/dota.py

Me having difficulty following along with when to use "steamToDota" "determineSteamid" might have had to do with me not knowing much about how steam ids are resolved and what a proper dota id looks like compared to a steam id. (I couldn't really access my dota ID at work when I was doing edits, so I was having trouble debugging that).

**Comment by imayhaveborkedit** [comment]
Oh right.  I probably could have mentioned somewhere that `dota_id = steam_id - 76561197960265728`.  Again, another part of the dota module I don't like.  I would honestly rather have a simple class with conversion methods for all of that I can use instead of keeping track of which one I need to use.

**Comment by imayhaveborkedit** [comment]
Half the stuff in the dota module is dead anyways because node-dota2 hasn't been updated to fully work with Source 2 yet.  When that rolls around i'll have plenty of work to do on the dota module which may just be a full rewrite of the entire module.

**Comment by GrappigPanda** [comment]
All right, well I'll probably just rewrite that module enough to get it working on other computers so that other's can run Borkedbot if they want.

If you want to delegate adding/adjusting anything else to this bot, I like the bot so I don't mind helping you with features. Just open an issue and if I can help, I'll help.

**Comment by imayhaveborkedit** [comment]
Redis comes to mind as one of the biggest issues, and the settings module by extension.  I'll add some random issues for some of the notable todos I have lying around.

**Comment by imayhaveborkedit** [comment]
Fun fact about `enabled_channels`, it's basically an artifact of my old mmr system that never got changed through all of the changes and additions to dota.py.

https://gist.github.com/imayhaveborkedit/d70df6ce72f3bb5d6e99

**Pull request merged**
